# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin', '0004_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SutraEntityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sutra_name', models.CharField(max_length=513, verbose_name='藏名称')),
                ('sutra_code', models.CharField(max_length=50, verbose_name='编码')),
                ('sutra_remark', models.CharField(max_length=1024, verbose_name='备注')),
            ],
        ),
    ]
